In [1]:
# report required packages
import pandas as pd
import numpy as np

In [8]:
# import dataset and exploratory data analysis
train_data = pd.read_csv('train.csv', index_col=0, nrows=50000)
val_data = pd.read_csv('test1.csv', index_col=0, nrows=10000)

In [9]:
train_data.head()

,android_id,apptype,carrier,dev_height,dev_ppi,dev_width,label,lan,media_id,ntt,os,osv,package,sid,timestamp,version,fea_hash,location,fea1_hash,cus_type
0,316361,1199,46000.0,0.0,0.0,0.0,1,NaN,104,6.0,android,9,18,1438873,1.559893e+12,8,2135019403,0,2329670524,601
1,135939,893,0.0,0.0,0.0,0.0,1,NaN,19,6.0,android,8.1,0,1185582,1.559994e+12,4,2782306428,1,2864801071,1000
2,399254,821,0.0,760.0,0.0,360.0,1,NaN,559,0.0,android,8.1.0,0,1555716,1.559837e+12,0,1392806005,2,628911675,696
3,68983,1004,46000.0,2214.0,0.0,1080.0,0,NaN,129,2.0,android,8.1.0,0,1093419,1.560042e+12,0,3562553457,3,1283809327,753
4,288999,1076,46000.0,2280.0,0.0,1080.0,1,zh-CN,64,2.0,android,8.0.0,0,1400089,1.559867e+12,5,2364522023,4,1510695983,582

In [11]:
train_data.describe()

,android_id,apptype,carrier,dev_height,dev_ppi,dev_width,label,media_id,ntt,package,sid,timestamp,location,fea1_hash,cus_type
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000,50000.000000,50000.000000,5.000000e+04,5.000000e+04,50000.000000,5.000000e+04,50000.000000
mean,263664.643380,986.915180,39990.793980,1265.563300,71.966580,706.33948,0.483480,125.819600,3.081260,38.890000,1.501860e+06,1.559813e+12,95.962320,2.302193e+09,733.488520
std,234004.898192,128.855027,15502.678561,853.349859,167.636445,507.50132,0.499732,167.247662,1.841848,134.689229,2.885645e+05,1.680306e+08,85.425662,1.235893e+09,332.245515
min,0.000000,95.000000,-1.000000,0.000000,0.000000,0.00000,0.000000,4.000000,0.000000,0.000000,1.000020e+06,1.559491e+12,-1.000000,1.510071e+07,297.000000
25%,0.000000,917.000000,46000.000000,720.000000,0.000000,360.00000,0.000000,29.000000,2.000000,0.000000,1.253772e+06,1.559663e+12,23.000000,1.376752e+09,411.000000
50%,233369.500000,1001.000000,46000.000000,1280.000000,0.000000,720.00000,0.000000,64.000000,2.000000,7.000000,1.501609e+06,1.559816e+12,64.000000,2.434219e+09,658.000000
75%,467871.750000,1076.000000,46000.000000,2038.000000,0.000000,1080.00000,1.000000,139.000000,5.000000,24.000000,1.752169e+06,1.559964e+12,155.000000,3.062465e+09,1019.000000
max,709859.000000,1238.000000,46003.000000,3180.000000,640.000000,2960.00000,1.000000,1524.000000,7.000000,2282.000000,1.999957e+06,1.560096e+12,328.000000,4.289392e+09,1380.000000

In [10]:
val_data.head()

,android_id,apptype,carrier,dev_height,dev_ppi,dev_width,lan,media_id,ntt,os,osv,package,sid,timestamp,version,fea_hash,location,fea1_hash,cus_type
0,317625,1181,46000.0,2196.0,2.0,1080.0,CN,639,2.0,Android,8.1.0,188,1440682,1.559872e+12,7,1672223856,57,3872258917,658
1,435108,944,46003.0,2280.0,3.0,1080.0,zh-CN,704,6.0,Android,8.1.0,221,1606824,1.559739e+12,3,3767901757,23,129322164,943
2,0,1106,46000.0,0.0,0.0,0.0,NaN,39,2.0,android,5.1,1562,1774642,1.559614e+12,0,454638703,30,4226678391,411
3,451504,761,46000.0,1344.0,0.0,720.0,NaN,54,2.0,android,7.1.1,9,1742535,1.559668e+12,0,1507622951,65,3355419572,848
4,0,1001,46000.0,665.0,0.0,320.0,zh-CN,29,5.0,Android,8.1.0,4,1689686,1.559694e+12,0,4116351093,148,2644467751,411